[repository]
name = "hyprclipx"
authors = ["Jan Ohlmann (azzuriel) <jan.ohlmann@hotmail.com>", "Leon Marzoll <leon.marzoll@gmail.com>"]

[hyprclipx]
description = "Layer-shell clipboard manager for Hyprland with GTK4 UI"
version = "0.1.0"
output = "build/hyprclipx.so"
build = [
    "cmake -DCMAKE_BUILD_TYPE=Release -B build",
    "cmake --build build",
    "mkdir -p $HOME/.local/bin && cp build/hyprclipx-ui $HOME/.local/bin/",
    "mkdir -p $HOME/.config/iconmanager/helpers && cp helpers/clipman-daemon.py $HOME/.config/iconmanager/helpers/"
]
